Document: libsomanetwork
Title: Debian libsomanetwork Manual
Author: <insert document author here>
Abstract: This manual describes what libsomanetwork is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libsomanetwork/libsomanetwork.sgml.gz

Format: postscript
Files: /usr/share/doc/libsomanetwork/libsomanetwork.ps.gz

Format: text
Files: /usr/share/doc/libsomanetwork/libsomanetwork.text.gz

Format: HTML
Index: /usr/share/doc/libsomanetwork/html/index.html
Files: /usr/share/doc/libsomanetwork/html/*.html

  
